### PR TITLE
Fix keccak256 precompile's compilation issue

### PR DESCRIPTION
**Pull request by jwasinger**
Master branch wasn't building before this fix.

### CODE REVIEW

**Comment by axic** [comment]
`master` is not building for me with or without this (but builds on CI):
```
   Compiling primitive-types v0.2.2 (https://github.com/paritytech/parity-common#f0348152)
error[E0433]: failed to resolve: could not find `OsRng` in `rand`
  --> /Users/alex/.cargo/git/checkouts/parity-common-b7e6dd3e48c6ce77/f034815/primitive-types/src/lib.rs:59:1
   |
59 | / construct_fixed_hash! {
60 | |     /// Fixed-size uninterpreted hash type with 20 bytes (160 bits) size.
61 | |     pub struct H160(20);
62 | | }
   | |_^ could not find `OsRng` in `rand`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by axic** [comment]
Is #59 building for you without changes?

**Comment by jwasinger** [comment]
Maybe you have to update your rust installation?  It builds for me on latest stable and nightly.

https://github.com/ewasm/ewasm-precompiles/pull/59 doesn't build.

**Comment by axic** [comment]
I have latest rustc, but I'm running this on stable and not nightly.

**Comment by axic** [comment]
This is obsolete by the new version of #59 but will merge it anyway.

**Pull request merged**
